# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Mail-SPF-Iterator
version:      1.05
version_from: lib/Mail/SPF/Iterator.pm
installdirs:  site
requires:
    Net::DNS:                      0.62
    URI:                           0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
